#!/bin/bash

set -e

script_dir="$(dirname $(readlink -f $0))"

function write_prologue()
{
    echo "# Generated by $(basename $0)" > "$out_file"
}

function write_empty()
{
    (
        echo ""
        echo "set("
        echo "    $1"
        echo "    \"\""
        echo ")"
    ) >> "$out_file"
}

function skip_ignored()
{
    if [ -z "$ignore_rules" ]; then
        cat
    else
        grep -viE "$ignore_rules"
    fi
}

function write_list()
{
    (
        printf '\nset(\n    %s\n' "$1"
        LC_ALL=C sort | uniq | skip_ignored | xargs -n1 --no-run-if-empty printf '    %s\n'
        printf ')\n'
    ) >> "$out_file"
}

function write_headers()
{
    var_name="$1"
    shift

    (
        for arg in "$@"; do
            ls $arg/*.h
        done
    ) | write_list "$var_name"
}

function write_vcxproj()
{
    "$script_dir/dump-vcxproj.sh" "$2" | write_list "$1"
}

function write_pbxproj()
{
    var_name="$1"
    shift
    "$script_dir/dump-pbxproj.sh" $* | write_list "$var_name"
}

ignore_rules=''

function dump_sdk_windows()
{
    out_file="cmake/SourcesWindows.cmake"
    write_prologue
    
    ignore_rules=''
    write_headers WTL_HEADERS wtl/Include

    ignore_rules='(pfc-fb2k-hooks\.(h|cpp))|(nix-objects\.(h|cpp))|(stdafx\.cpp)'
    write_headers PFC_HEADERS sdk/pfc
    write_vcxproj PFC_SOURCES sdk/pfc/pfc.vcxproj

    ignore_rules=''
    write_headers SHARED_HEADERS sdk/foobar2000/shared
    write_empty   SHARED_SOURCES

    ignore_rules=''
    write_headers SDK_HEADERS sdk/foobar2000/SDK
    write_vcxproj SDK_SOURCES sdk/foobar2000/SDK/foobar2000_SDK.vcxproj

    ignore_rules='(stdafx\.cpp)'
    write_headers SDK_HELPERS_HEADERS sdk/foobar2000/helpers
    write_vcxproj SDK_HELPERS_SOURCES sdk/foobar2000/helpers/foobar2000_sdk_helpers.vcxproj

    ignore_rules=''
    write_headers PPUI_HEADERS sdk/libPPUI
    write_vcxproj PPUI_SOURCES sdk/libPPUI/libPPUI.vcxproj

    ignore_rules=''
    write_vcxproj COMPONENT_CLIENT_SOURCES \
        sdk/foobar2000/foobar2000_component_client/foobar2000_component_client.vcxproj

    ignore_rules='(stdafx\.h)|(PCH\.cpp)'
    write_headers SAMPLE_HEADERS sdk/foobar2000/foo_sample
    write_vcxproj SAMPLE_SOURCES sdk/foobar2000/foo_sample/foo_sample.vcxproj
}

function dump_sdk_macos()
{
    out_file="cmake/SourcesMacOs.cmake"

    write_prologue

    ignore_rules='(stdafx\.cpp)'
    write_headers PFC_HEADERS sdk/pfc
    write_pbxproj PFC_SOURCES sdk/pfc/pfc.xcodeproj

    ignore_rules=''
    write_headers SHARED_HEADERS sdk/foobar2000/shared
    write_pbxproj SHARED_SOURCES sdk/foobar2000/shared/shared.xcodeproj

    ignore_rules=''
    write_headers SDK_HEADERS sdk/foobar2000/SDK
    write_pbxproj SDK_SOURCES sdk/foobar2000/SDK/foobar2000_SDK.xcodeproj

    ignore_rules='(stdafx\.cpp)'
    write_headers SDK_HELPERS_HEADERS sdk/foobar2000/helpers
    write_pbxproj SDK_HELPERS_SOURCES sdk/foobar2000/helpers/foobar2000_SDK_helpers.xcodeproj

    ignore_rules=''
    write_pbxproj COMPONENT_CLIENT_SOURCES \
        sdk/foobar2000/foobar2000_component_client/foobar2000_component_client.xcodeproj

    ignore_rules='(stdafx\.h)|(PCH\.cpp)'

    write_headers SAMPLE_HEADERS \
        sdk/foobar2000/foo_sample \
        sdk/foobar2000/helpers-mac

    write_pbxproj SAMPLE_SOURCES \
        sdk/foobar2000/foo_sample/foo_sample.xcodeproj \
        sdk/foobar2000/helpers-mac \
        sdk/foobar2000/foo_sample/Mac
}

cd "$script_dir/.."

dump_sdk_windows
dump_sdk_macos

