#!/bin/bash

set -e

script_dir="$(dirname $(readlink -f $0))"

function write_prologue()
{
    echo "# Generated by $(basename $0)" >> "$out_file"
}

function write_empty()
{
    (
        echo ""
        echo "set("
        echo "    $1"
        echo "    \"\""
        echo ")"
    ) >> "$out_file"
}

function write_list()
{
    ignore_rules=$2

    if [ -z "$ignore_rules" ]; then
        ignore_rules='$^'
    fi

    (
        printf '\nset(\n    %s\n' "$1"
        LC_ALL=C sort | uniq | grep -viE "$ignore_rules" | xargs -n1 --no-run-if-empty printf '    %s\n'
        printf ')\n'
    ) >> "$out_file"
}

function write_headers()
{
    ls $2/*.h | write_list "$1" "$3"
}

function write_vcxproj()
{
    "$script_dir/dump-vcxproj.sh" "$2" | write_list "$1" "$3"
}

function write_pbxproj()
{
    "$script_dir/dump-pbxproj.sh" "$2" "$4" "$5" | write_list "$1" "$3"
}

function dump_sdk_windows()
{
    out_file="cmake/SourcesWindows.cmake"
    rm -f $out_file || true

    write_prologue
    
    write_headers WTL_HEADERS wtl/Include

    write_headers PFC_HEADERS sdk/pfc '(pfc-fb2k-hooks\.h)|(nix-objects\.h)'
    write_vcxproj PFC_SOURCES sdk/pfc/pfc.vcxproj '(stdafx\.cpp)|(pfc-fb2k-hooks\.cpp)|(nix-objects\.cpp)'

    write_headers SHARED_HEADERS sdk/foobar2000/shared
    write_empty   SHARED_SOURCES

    write_headers SDK_HEADERS sdk/foobar2000/SDK
    write_vcxproj SDK_SOURCES sdk/foobar2000/SDK/foobar2000_SDK.vcxproj

    write_headers SDK_HELPERS_HEADERS sdk/foobar2000/helpers
    write_vcxproj SDK_HELPERS_SOURCES sdk/foobar2000/helpers/foobar2000_sdk_helpers.vcxproj '(stdafx\.cpp)'

    write_headers PPUI_HEADERS sdk/libPPUI
    write_vcxproj PPUI_SOURCES sdk/libPPUI/libPPUI.vcxproj

    write_vcxproj COMPONENT_CLIENT_SOURCES \
        sdk/foobar2000/foobar2000_component_client/foobar2000_component_client.vcxproj

    write_headers SAMPLE_HEADERS sdk/foobar2000/foo_sample '(stdafx\.h)'
    write_vcxproj SAMPLE_SOURCES sdk/foobar2000/foo_sample/foo_sample.vcxproj '(PCH\.cpp)'
}

function dump_sdk_macos()
{
    out_file="cmake/SourcesMacOs.cmake"
    rm -f $out_file || true

    write_prologue

    write_headers PFC_HEADERS sdk/pfc
    write_pbxproj PFC_SOURCES sdk/pfc/pfc.xcodeproj '(stdafx\.cpp)'

    write_headers SHARED_HEADERS sdk/foobar2000/shared
    write_pbxproj SHARED_SOURCES sdk/foobar2000/shared/shared.xcodeproj

    write_headers SDK_HEADERS sdk/foobar2000/SDK
    write_pbxproj SDK_SOURCES sdk/foobar2000/SDK/foobar2000_SDK.xcodeproj

    write_headers SDK_HELPERS_HEADERS sdk/foobar2000/helpers
    write_pbxproj SDK_HELPERS_SOURCES sdk/foobar2000/helpers/foobar2000_SDK_helpers.xcodeproj '(stdafx\.cpp)'

    write_pbxproj COMPONENT_CLIENT_SOURCES \
        sdk/foobar2000/foobar2000_component_client/foobar2000_component_client.xcodeproj

    write_headers SAMPLE_HEADERS sdk/foobar2000/foo_sample '(stdafx\.h)'
    write_pbxproj SAMPLE_SOURCES sdk/foobar2000/foo_sample/foo_sample.xcodeproj '(PCH\.cpp)' \
        sdk/foobar2000/helpers-mac \
        sdk/foobar2000/foo_sample/Mac
}

cd "$script_dir/.."

dump_sdk_windows
dump_sdk_macos

